package com.graphapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EdgeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdgeAllPropertiesEquals(Edge expected, Edge actual) {
        assertEdgeAutoGeneratedPropertiesEquals(expected, actual);
        assertEdgeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdgeAllUpdatablePropertiesEquals(Edge expected, Edge actual) {
        assertEdgeUpdatableFieldsEquals(expected, actual);
        assertEdgeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdgeAutoGeneratedPropertiesEquals(Edge expected, Edge actual) {
        assertThat(actual)
            .as("Verify Edge auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdgeUpdatableFieldsEquals(Edge expected, Edge actual) {
        assertThat(actual)
            .as("Verify Edge relevant properties")
            .satisfies(a -> assertThat(a.getWeight()).as("check weight").isEqualTo(expected.getWeight()))
            .satisfies(a -> assertThat(a.getDirected()).as("check directed").isEqualTo(expected.getDirected()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEdgeUpdatableRelationshipsEquals(Edge expected, Edge actual) {
        assertThat(actual)
            .as("Verify Edge relationships")
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getTarget()).as("check target").isEqualTo(expected.getTarget()))
            .satisfies(a -> assertThat(a.getGraph()).as("check graph").isEqualTo(expected.getGraph()));
    }
}
