package com.graphapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GraphAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGraphAllPropertiesEquals(Graph expected, Graph actual) {
        assertGraphAutoGeneratedPropertiesEquals(expected, actual);
        assertGraphAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGraphAllUpdatablePropertiesEquals(Graph expected, Graph actual) {
        assertGraphUpdatableFieldsEquals(expected, actual);
        assertGraphUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGraphAutoGeneratedPropertiesEquals(Graph expected, Graph actual) {
        assertThat(actual)
            .as("Verify Graph auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGraphUpdatableFieldsEquals(Graph expected, Graph actual) {
        assertThat(actual)
            .as("Verify Graph relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGraphUpdatableRelationshipsEquals(Graph expected, Graph actual) {
        // empty method
    }
}
