package com.graphapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NodeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeAllPropertiesEquals(Node expected, Node actual) {
        assertNodeAutoGeneratedPropertiesEquals(expected, actual);
        assertNodeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeAllUpdatablePropertiesEquals(Node expected, Node actual) {
        assertNodeUpdatableFieldsEquals(expected, actual);
        assertNodeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeAutoGeneratedPropertiesEquals(Node expected, Node actual) {
        assertThat(actual)
            .as("Verify Node auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeUpdatableFieldsEquals(Node expected, Node actual) {
        assertThat(actual)
            .as("Verify Node relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getX()).as("check x").isEqualTo(expected.getX()))
            .satisfies(a -> assertThat(a.getY()).as("check y").isEqualTo(expected.getY()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNodeUpdatableRelationshipsEquals(Node expected, Node actual) {
        assertThat(actual)
            .as("Verify Node relationships")
            .satisfies(a -> assertThat(a.getGraph()).as("check graph").isEqualTo(expected.getGraph()));
    }
}
